/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.ude.poo.empresas.vistas.gui;
import java.awt.Toolkit;
import javax.swing.*;
/**
 *
 * @author david
 */
public class VentanaPrincipal extends JFrame {

    /**
     * Creates new form VentanaPrincipal
     */    
    public VentanaPrincipal() {
        
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        Seticon();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new co.edu.ude.poo.empresas.vistas.gui.Background();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArea = new javax.swing.JMenu();
        ItemAgregarArea = new javax.swing.JMenuItem();
        ItemBuscarArea = new javax.swing.JMenuItem();
        ItemEditarArea = new javax.swing.JMenuItem();
        ItemEliminarArea = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        SubMenuReportesArea = new javax.swing.JMenu();
        ItemListarTodoArea = new javax.swing.JMenuItem();
        ItemListarPorIdArea = new javax.swing.JMenuItem();
        ItemListarPorNombreArea = new javax.swing.JMenuItem();
        MenuAsesor = new javax.swing.JMenu();
        ItemAgregarAsesor = new javax.swing.JMenuItem();
        ItemBuscarAsesor = new javax.swing.JMenuItem();
        ItemEditarAsesor = new javax.swing.JMenuItem();
        ItemEliminarAsesor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        SubMenuReportesAsesor = new javax.swing.JMenu();
        ItemListarTodoAsesor = new javax.swing.JMenuItem();
        ItemListarPorIdAsesor = new javax.swing.JMenuItem();
        ItemListarPorFechaInicioAsesor = new javax.swing.JMenuItem();
        ItemListarPorNombreAsesor = new javax.swing.JMenuItem();
        ItemListarPorDireccionAsesor = new javax.swing.JMenuItem();
        ItemListarPorTitulaciónAsesor = new javax.swing.JMenuItem();
        MenuEmpresa = new javax.swing.JMenu();
        ItemAgregarEmpresa = new javax.swing.JMenuItem();
        ItemBuscarEmpresa = new javax.swing.JMenuItem();
        ItemEditarEmpresa = new javax.swing.JMenuItem();
        ItemEliminarEmpresa = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        SubMenuReportesEmpresa = new javax.swing.JMenu();
        ItemListarTodoEmpresa = new javax.swing.JMenuItem();
        ItemListarPorIdEmpresa = new javax.swing.JMenuItem();
        ItemListarPorNombreEmpresa = new javax.swing.JMenuItem();
        ItemListarPorFechaEntradaEmpresa = new javax.swing.JMenuItem();
        ItemListarPorFacturacionAnualEmpresa = new javax.swing.JMenuItem();
        ItemListarPorNumeroVendedoresEmpresa = new javax.swing.JMenuItem();
        ItemListarPorNUmeroSedesEmpresa = new javax.swing.JMenuItem();
        MenuHolding = new javax.swing.JMenu();
        ItemAgregarHolding = new javax.swing.JMenuItem();
        ItemBuscarHolding = new javax.swing.JMenuItem();
        ItemEditarHolding = new javax.swing.JMenuItem();
        ItemEliminarHolding = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        SubMenuReportesHolding = new javax.swing.JMenu();
        ItemListarTodoHolding = new javax.swing.JMenuItem();
        ItemListarPorIdHolding = new javax.swing.JMenuItem();
        ItemListarPorNombreHolding = new javax.swing.JMenuItem();
        MenuPais = new javax.swing.JMenu();
        ItemAgregarPais = new javax.swing.JMenuItem();
        ItemBuscarPais = new javax.swing.JMenuItem();
        ItemEditarPais = new javax.swing.JMenuItem();
        ItemEliminarPais = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        SubMenuReportesPais = new javax.swing.JMenu();
        ItemListarTodoPais = new javax.swing.JMenuItem();
        ItemListarPorIdPais = new javax.swing.JMenuItem();
        ItemListarPorNombrePais = new javax.swing.JMenuItem();
        ItemListarPorCapitalPais = new javax.swing.JMenuItem();
        ItemListarPorNumeroHabitantesPais = new javax.swing.JMenuItem();
        ItemListarPorPibPais = new javax.swing.JMenuItem();
        MenuSede = new javax.swing.JMenu();
        ItemAgregarSede = new javax.swing.JMenuItem();
        ItemBuscarSede = new javax.swing.JMenuItem();
        ItemEditarSede = new javax.swing.JMenuItem();
        ItemEliminarSede = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        SubMenuReportesSede = new javax.swing.JMenu();
        ItemListarTodoSede = new javax.swing.JMenuItem();
        ItemListarPorIdSede = new javax.swing.JMenuItem();
        ItemListarPorCiudadLocalizaSede = new javax.swing.JMenuItem();
        MenuVendedor = new javax.swing.JMenu();
        ItemAgregarVendedor = new javax.swing.JMenuItem();
        ItemBuscarVendedor = new javax.swing.JMenuItem();
        ItemEditarVendedor = new javax.swing.JMenuItem();
        ItemEliminarVendedor = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        SubMenuReportesVendedor = new javax.swing.JMenu();
        ItemListarTodoVendedor = new javax.swing.JMenuItem();
        ItemListarPorIdVendedor = new javax.swing.JMenuItem();
        ItemListarPorNombreVendedor = new javax.swing.JMenuItem();
        ItemListarPorDireccionVendedor = new javax.swing.JMenuItem();
        ItemListarPorNumeroTrabajosVendedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("..: Gestión del Holding :..");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1048, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        MenuArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/area24px.png"))); // NOI18N
        MenuArea.setText("Area");
        MenuArea.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        ItemAgregarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/agregar24px.png"))); // NOI18N
        ItemAgregarArea.setText("Agregar...");
        ItemAgregarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAgregarAreaActionPerformed(evt);
            }
        });
        MenuArea.add(ItemAgregarArea);

        ItemBuscarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/buscar24px.png"))); // NOI18N
        ItemBuscarArea.setText("Buscar...");
        ItemBuscarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemBuscarAreaActionPerformed(evt);
            }
        });
        MenuArea.add(ItemBuscarArea);

        ItemEditarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/editar24px.png"))); // NOI18N
        ItemEditarArea.setText("Editar...");
        ItemEditarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEditarAreaActionPerformed(evt);
            }
        });
        MenuArea.add(ItemEditarArea);

        ItemEliminarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/eliminar24px.png"))); // NOI18N
        ItemEliminarArea.setText("Eliminar...");
        ItemEliminarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEliminarAreaActionPerformed(evt);
            }
        });
        MenuArea.add(ItemEliminarArea);
        MenuArea.add(jSeparator1);

        SubMenuReportesArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/reporte24px.png"))); // NOI18N
        SubMenuReportesArea.setText("Reportes");

        ItemListarTodoArea.setText("Listar Todo...");
        SubMenuReportesArea.add(ItemListarTodoArea);

        ItemListarPorIdArea.setText("Listar por Id...");
        ItemListarPorIdArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorIdAreaActionPerformed(evt);
            }
        });
        SubMenuReportesArea.add(ItemListarPorIdArea);

        ItemListarPorNombreArea.setText("Listar por Nombre...");
        ItemListarPorNombreArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorNombreAreaActionPerformed(evt);
            }
        });
        SubMenuReportesArea.add(ItemListarPorNombreArea);

        MenuArea.add(SubMenuReportesArea);

        jMenuBar1.add(MenuArea);

        MenuAsesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/asesor24px.png"))); // NOI18N
        MenuAsesor.setText("Asesor");
        MenuAsesor.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        ItemAgregarAsesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/agregar24px.png"))); // NOI18N
        ItemAgregarAsesor.setText("Agregar...");
        ItemAgregarAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAgregarAsesorActionPerformed(evt);
            }
        });
        MenuAsesor.add(ItemAgregarAsesor);

        ItemBuscarAsesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/buscar24px.png"))); // NOI18N
        ItemBuscarAsesor.setText("Buscar...");
        ItemBuscarAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemBuscarAsesorActionPerformed(evt);
            }
        });
        MenuAsesor.add(ItemBuscarAsesor);

        ItemEditarAsesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/editar24px.png"))); // NOI18N
        ItemEditarAsesor.setText("Editar...");
        ItemEditarAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEditarAsesorActionPerformed(evt);
            }
        });
        MenuAsesor.add(ItemEditarAsesor);

        ItemEliminarAsesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/eliminar24px.png"))); // NOI18N
        ItemEliminarAsesor.setText("Eliminar...");
        ItemEliminarAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEliminarAsesorActionPerformed(evt);
            }
        });
        MenuAsesor.add(ItemEliminarAsesor);
        MenuAsesor.add(jSeparator2);

        SubMenuReportesAsesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/reporte24px.png"))); // NOI18N
        SubMenuReportesAsesor.setText("Reportes");

        ItemListarTodoAsesor.setText("Listar Todo...");
        SubMenuReportesAsesor.add(ItemListarTodoAsesor);

        ItemListarPorIdAsesor.setText("Listar por Id...");
        ItemListarPorIdAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorIdAsesorActionPerformed(evt);
            }
        });
        SubMenuReportesAsesor.add(ItemListarPorIdAsesor);

        ItemListarPorFechaInicioAsesor.setText("Listar por Fecha de inicio...");
        ItemListarPorFechaInicioAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorFechaInicioAsesorActionPerformed(evt);
            }
        });
        SubMenuReportesAsesor.add(ItemListarPorFechaInicioAsesor);

        ItemListarPorNombreAsesor.setText("Listar por Nombre...");
        ItemListarPorNombreAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorNombreAsesorActionPerformed(evt);
            }
        });
        SubMenuReportesAsesor.add(ItemListarPorNombreAsesor);

        ItemListarPorDireccionAsesor.setText("Listar por Dirección...");
        ItemListarPorDireccionAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorDireccionAsesorActionPerformed(evt);
            }
        });
        SubMenuReportesAsesor.add(ItemListarPorDireccionAsesor);

        ItemListarPorTitulaciónAsesor.setText("Listar por Titulación...");
        ItemListarPorTitulaciónAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorTitulaciónAsesorActionPerformed(evt);
            }
        });
        SubMenuReportesAsesor.add(ItemListarPorTitulaciónAsesor);

        MenuAsesor.add(SubMenuReportesAsesor);

        jMenuBar1.add(MenuAsesor);

        MenuEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/empresa24px.png"))); // NOI18N
        MenuEmpresa.setText("Empresa");
        MenuEmpresa.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        ItemAgregarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/agregar24px.png"))); // NOI18N
        ItemAgregarEmpresa.setText("Agregar...");
        ItemAgregarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAgregarEmpresaActionPerformed(evt);
            }
        });
        MenuEmpresa.add(ItemAgregarEmpresa);

        ItemBuscarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/buscar24px.png"))); // NOI18N
        ItemBuscarEmpresa.setText("Buscar...");
        ItemBuscarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemBuscarEmpresaActionPerformed(evt);
            }
        });
        MenuEmpresa.add(ItemBuscarEmpresa);

        ItemEditarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/editar24px.png"))); // NOI18N
        ItemEditarEmpresa.setText("Editar...");
        ItemEditarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEditarEmpresaActionPerformed(evt);
            }
        });
        MenuEmpresa.add(ItemEditarEmpresa);

        ItemEliminarEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/eliminar24px.png"))); // NOI18N
        ItemEliminarEmpresa.setText("Eliminar...");
        ItemEliminarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEliminarEmpresaActionPerformed(evt);
            }
        });
        MenuEmpresa.add(ItemEliminarEmpresa);
        MenuEmpresa.add(jSeparator3);

        SubMenuReportesEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/reporte24px.png"))); // NOI18N
        SubMenuReportesEmpresa.setText("Reportes");

        ItemListarTodoEmpresa.setText("Listar Todo...");
        SubMenuReportesEmpresa.add(ItemListarTodoEmpresa);

        ItemListarPorIdEmpresa.setText("Listar por Id...");
        ItemListarPorIdEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorIdEmpresaActionPerformed(evt);
            }
        });
        SubMenuReportesEmpresa.add(ItemListarPorIdEmpresa);

        ItemListarPorNombreEmpresa.setText("Listar por Nombre...");
        ItemListarPorNombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorNombreEmpresaActionPerformed(evt);
            }
        });
        SubMenuReportesEmpresa.add(ItemListarPorNombreEmpresa);

        ItemListarPorFechaEntradaEmpresa.setText("Listar por Fecha de entrada...");
        ItemListarPorFechaEntradaEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorFechaEntradaEmpresaActionPerformed(evt);
            }
        });
        SubMenuReportesEmpresa.add(ItemListarPorFechaEntradaEmpresa);

        ItemListarPorFacturacionAnualEmpresa.setText("Listar por Facturación anual...");
        ItemListarPorFacturacionAnualEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorFacturacionAnualEmpresaActionPerformed(evt);
            }
        });
        SubMenuReportesEmpresa.add(ItemListarPorFacturacionAnualEmpresa);

        ItemListarPorNumeroVendedoresEmpresa.setText("Listar por Numero de vendedores...");
        ItemListarPorNumeroVendedoresEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorNumeroVendedoresEmpresaActionPerformed(evt);
            }
        });
        SubMenuReportesEmpresa.add(ItemListarPorNumeroVendedoresEmpresa);

        ItemListarPorNUmeroSedesEmpresa.setText("Listar por Numero de sedes...");
        ItemListarPorNUmeroSedesEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorNUmeroSedesEmpresaActionPerformed(evt);
            }
        });
        SubMenuReportesEmpresa.add(ItemListarPorNUmeroSedesEmpresa);

        MenuEmpresa.add(SubMenuReportesEmpresa);

        jMenuBar1.add(MenuEmpresa);

        MenuHolding.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/holding24px.png"))); // NOI18N
        MenuHolding.setText("Holding");
        MenuHolding.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        ItemAgregarHolding.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/agregar24px.png"))); // NOI18N
        ItemAgregarHolding.setText("Agregar...");
        ItemAgregarHolding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAgregarHoldingActionPerformed(evt);
            }
        });
        MenuHolding.add(ItemAgregarHolding);

        ItemBuscarHolding.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/buscar24px.png"))); // NOI18N
        ItemBuscarHolding.setText("Buscar...");
        ItemBuscarHolding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemBuscarHoldingActionPerformed(evt);
            }
        });
        MenuHolding.add(ItemBuscarHolding);

        ItemEditarHolding.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/editar24px.png"))); // NOI18N
        ItemEditarHolding.setText("Editar...");
        ItemEditarHolding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEditarHoldingActionPerformed(evt);
            }
        });
        MenuHolding.add(ItemEditarHolding);

        ItemEliminarHolding.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/eliminar24px.png"))); // NOI18N
        ItemEliminarHolding.setText("Eliminar...");
        ItemEliminarHolding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEliminarHoldingActionPerformed(evt);
            }
        });
        MenuHolding.add(ItemEliminarHolding);
        MenuHolding.add(jSeparator6);

        SubMenuReportesHolding.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/reporte24px.png"))); // NOI18N
        SubMenuReportesHolding.setText("Reportes");

        ItemListarTodoHolding.setText("Listar Todo...");
        SubMenuReportesHolding.add(ItemListarTodoHolding);

        ItemListarPorIdHolding.setText("Listar por Id...");
        ItemListarPorIdHolding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorIdHoldingActionPerformed(evt);
            }
        });
        SubMenuReportesHolding.add(ItemListarPorIdHolding);

        ItemListarPorNombreHolding.setText("Listar por Nombre...");
        ItemListarPorNombreHolding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorNombreHoldingActionPerformed(evt);
            }
        });
        SubMenuReportesHolding.add(ItemListarPorNombreHolding);

        MenuHolding.add(SubMenuReportesHolding);

        jMenuBar1.add(MenuHolding);

        MenuPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/pais24px.png"))); // NOI18N
        MenuPais.setText("Pais");
        MenuPais.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        ItemAgregarPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/agregar24px.png"))); // NOI18N
        ItemAgregarPais.setText("Agregar...");
        ItemAgregarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAgregarPaisActionPerformed(evt);
            }
        });
        MenuPais.add(ItemAgregarPais);

        ItemBuscarPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/buscar24px.png"))); // NOI18N
        ItemBuscarPais.setText("Buscar...");
        ItemBuscarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemBuscarPaisActionPerformed(evt);
            }
        });
        MenuPais.add(ItemBuscarPais);

        ItemEditarPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/editar24px.png"))); // NOI18N
        ItemEditarPais.setText("Editar...");
        ItemEditarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEditarPaisActionPerformed(evt);
            }
        });
        MenuPais.add(ItemEditarPais);

        ItemEliminarPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/eliminar24px.png"))); // NOI18N
        ItemEliminarPais.setText("Eliminar...");
        ItemEliminarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEliminarPaisActionPerformed(evt);
            }
        });
        MenuPais.add(ItemEliminarPais);
        MenuPais.add(jSeparator4);

        SubMenuReportesPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/reporte24px.png"))); // NOI18N
        SubMenuReportesPais.setText("Reportes");

        ItemListarTodoPais.setText("Listar Todo...");
        SubMenuReportesPais.add(ItemListarTodoPais);

        ItemListarPorIdPais.setText("Listar por Id...");
        ItemListarPorIdPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorIdPaisActionPerformed(evt);
            }
        });
        SubMenuReportesPais.add(ItemListarPorIdPais);

        ItemListarPorNombrePais.setText("Listar por Nombre...");
        ItemListarPorNombrePais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorNombrePaisActionPerformed(evt);
            }
        });
        SubMenuReportesPais.add(ItemListarPorNombrePais);

        ItemListarPorCapitalPais.setText("Listar por Capital...");
        ItemListarPorCapitalPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorCapitalPaisActionPerformed(evt);
            }
        });
        SubMenuReportesPais.add(ItemListarPorCapitalPais);

        ItemListarPorNumeroHabitantesPais.setText("Listar por Numero de habitantes...");
        ItemListarPorNumeroHabitantesPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorNumeroHabitantesPaisActionPerformed(evt);
            }
        });
        SubMenuReportesPais.add(ItemListarPorNumeroHabitantesPais);

        ItemListarPorPibPais.setText("Listar por PIB...");
        ItemListarPorPibPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorPibPaisActionPerformed(evt);
            }
        });
        SubMenuReportesPais.add(ItemListarPorPibPais);

        MenuPais.add(SubMenuReportesPais);

        jMenuBar1.add(MenuPais);

        MenuSede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/sede24px.png"))); // NOI18N
        MenuSede.setText("Sede");
        MenuSede.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        ItemAgregarSede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/agregar24px.png"))); // NOI18N
        ItemAgregarSede.setText("Agregar...");
        ItemAgregarSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAgregarSedeActionPerformed(evt);
            }
        });
        MenuSede.add(ItemAgregarSede);

        ItemBuscarSede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/buscar24px.png"))); // NOI18N
        ItemBuscarSede.setText("Buscar...");
        ItemBuscarSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemBuscarSedeActionPerformed(evt);
            }
        });
        MenuSede.add(ItemBuscarSede);

        ItemEditarSede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/editar24px.png"))); // NOI18N
        ItemEditarSede.setText("Editar...");
        ItemEditarSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEditarSedeActionPerformed(evt);
            }
        });
        MenuSede.add(ItemEditarSede);

        ItemEliminarSede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/eliminar24px.png"))); // NOI18N
        ItemEliminarSede.setText("Eliminar...");
        ItemEliminarSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEliminarSedeActionPerformed(evt);
            }
        });
        MenuSede.add(ItemEliminarSede);
        MenuSede.add(jSeparator5);

        SubMenuReportesSede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/reporte24px.png"))); // NOI18N
        SubMenuReportesSede.setText("Reportes");

        ItemListarTodoSede.setText("Listar Todo...");
        SubMenuReportesSede.add(ItemListarTodoSede);

        ItemListarPorIdSede.setText("Listar por Id...");
        ItemListarPorIdSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorIdSedeActionPerformed(evt);
            }
        });
        SubMenuReportesSede.add(ItemListarPorIdSede);

        ItemListarPorCiudadLocalizaSede.setText("Listar por Ciudad donde se localiza...");
        ItemListarPorCiudadLocalizaSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorCiudadLocalizaSedeActionPerformed(evt);
            }
        });
        SubMenuReportesSede.add(ItemListarPorCiudadLocalizaSede);

        MenuSede.add(SubMenuReportesSede);

        jMenuBar1.add(MenuSede);

        MenuVendedor.setText("Vendedor");
        MenuVendedor.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        ItemAgregarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/agregar24px.png"))); // NOI18N
        ItemAgregarVendedor.setText("Agregar...");
        ItemAgregarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAgregarVendedorActionPerformed(evt);
            }
        });
        MenuVendedor.add(ItemAgregarVendedor);

        ItemBuscarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/buscar24px.png"))); // NOI18N
        ItemBuscarVendedor.setText("Buscar...");
        ItemBuscarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemBuscarVendedorActionPerformed(evt);
            }
        });
        MenuVendedor.add(ItemBuscarVendedor);

        ItemEditarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/editar24px.png"))); // NOI18N
        ItemEditarVendedor.setText("Editar...");
        ItemEditarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEditarVendedorActionPerformed(evt);
            }
        });
        MenuVendedor.add(ItemEditarVendedor);

        ItemEliminarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/eliminar24px.png"))); // NOI18N
        ItemEliminarVendedor.setText("Eliminar...");
        ItemEliminarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemEliminarVendedorActionPerformed(evt);
            }
        });
        MenuVendedor.add(ItemEliminarVendedor);
        MenuVendedor.add(jSeparator7);

        SubMenuReportesVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/reporte24px.png"))); // NOI18N
        SubMenuReportesVendedor.setText("Reportes");

        ItemListarTodoVendedor.setText("Listar Todo...");
        SubMenuReportesVendedor.add(ItemListarTodoVendedor);

        ItemListarPorIdVendedor.setText("Listar por Id...");
        ItemListarPorIdVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorIdVendedorActionPerformed(evt);
            }
        });
        SubMenuReportesVendedor.add(ItemListarPorIdVendedor);

        ItemListarPorNombreVendedor.setText("Listar por Nombre...");
        ItemListarPorNombreVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorNombreVendedorActionPerformed(evt);
            }
        });
        SubMenuReportesVendedor.add(ItemListarPorNombreVendedor);

        ItemListarPorDireccionVendedor.setText("Listar por Dirección...");
        ItemListarPorDireccionVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorDireccionVendedorActionPerformed(evt);
            }
        });
        SubMenuReportesVendedor.add(ItemListarPorDireccionVendedor);

        ItemListarPorNumeroTrabajosVendedor.setText("Listar por Numero de trabajos...");
        ItemListarPorNumeroTrabajosVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemListarPorNumeroTrabajosVendedorActionPerformed(evt);
            }
        });
        SubMenuReportesVendedor.add(ItemListarPorNumeroTrabajosVendedor);

        MenuVendedor.add(SubMenuReportesVendedor);

        jMenuBar1.add(MenuVendedor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemAgregarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAgregarAreaActionPerformed
        VentanaCrudArea ventana_area = new VentanaCrudArea(this, true);
        ventana_area.setLocationRelativeTo(this);
        ventana_area.setVisible(true);
    }//GEN-LAST:event_ItemAgregarAreaActionPerformed

    private void ItemBuscarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemBuscarAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemBuscarAreaActionPerformed

    private void ItemEditarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEditarAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemEditarAreaActionPerformed

    private void ItemEliminarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEliminarAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemEliminarAreaActionPerformed

    private void ItemListarPorIdAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorIdAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorIdAreaActionPerformed

    private void ItemListarPorNombreAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorNombreAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorNombreAreaActionPerformed

    private void ItemAgregarAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAgregarAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemAgregarAsesorActionPerformed

    private void ItemBuscarAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemBuscarAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemBuscarAsesorActionPerformed

    private void ItemEditarAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEditarAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemEditarAsesorActionPerformed

    private void ItemEliminarAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEliminarAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemEliminarAsesorActionPerformed

    private void ItemListarPorIdAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorIdAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorIdAsesorActionPerformed

    private void ItemListarPorFechaInicioAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorFechaInicioAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorFechaInicioAsesorActionPerformed

    private void ItemAgregarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAgregarEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemAgregarEmpresaActionPerformed

    private void ItemBuscarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemBuscarEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemBuscarEmpresaActionPerformed

    private void ItemEditarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEditarEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemEditarEmpresaActionPerformed

    private void ItemEliminarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEliminarEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemEliminarEmpresaActionPerformed

    private void ItemListarPorIdEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorIdEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorIdEmpresaActionPerformed

    private void ItemListarPorNombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorNombreEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorNombreEmpresaActionPerformed

    private void ItemAgregarHoldingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAgregarHoldingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemAgregarHoldingActionPerformed

    private void ItemBuscarHoldingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemBuscarHoldingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemBuscarHoldingActionPerformed

    private void ItemEditarHoldingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEditarHoldingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemEditarHoldingActionPerformed

    private void ItemEliminarHoldingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEliminarHoldingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemEliminarHoldingActionPerformed

    private void ItemListarPorIdHoldingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorIdHoldingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorIdHoldingActionPerformed

    private void ItemListarPorNombreHoldingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorNombreHoldingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorNombreHoldingActionPerformed

    private void ItemAgregarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAgregarPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemAgregarPaisActionPerformed

    private void ItemBuscarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemBuscarPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemBuscarPaisActionPerformed

    private void ItemEditarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEditarPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemEditarPaisActionPerformed

    private void ItemEliminarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEliminarPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemEliminarPaisActionPerformed

    private void ItemListarPorIdPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorIdPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorIdPaisActionPerformed

    private void ItemListarPorNombrePaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorNombrePaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorNombrePaisActionPerformed

    private void ItemAgregarSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAgregarSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemAgregarSedeActionPerformed

    private void ItemBuscarSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemBuscarSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemBuscarSedeActionPerformed

    private void ItemEditarSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEditarSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemEditarSedeActionPerformed

    private void ItemEliminarSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEliminarSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemEliminarSedeActionPerformed

    private void ItemListarPorIdSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorIdSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorIdSedeActionPerformed

    private void ItemListarPorCiudadLocalizaSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorCiudadLocalizaSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorCiudadLocalizaSedeActionPerformed

    private void ItemAgregarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAgregarVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemAgregarVendedorActionPerformed

    private void ItemBuscarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemBuscarVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemBuscarVendedorActionPerformed

    private void ItemEditarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEditarVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemEditarVendedorActionPerformed

    private void ItemEliminarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemEliminarVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemEliminarVendedorActionPerformed

    private void ItemListarPorIdVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorIdVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorIdVendedorActionPerformed

    private void ItemListarPorNombreVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorNombreVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorNombreVendedorActionPerformed

    private void ItemListarPorNombreAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorNombreAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorNombreAsesorActionPerformed

    private void ItemListarPorDireccionAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorDireccionAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorDireccionAsesorActionPerformed

    private void ItemListarPorTitulaciónAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorTitulaciónAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorTitulaciónAsesorActionPerformed

    private void ItemListarPorFechaEntradaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorFechaEntradaEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorFechaEntradaEmpresaActionPerformed

    private void ItemListarPorFacturacionAnualEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorFacturacionAnualEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorFacturacionAnualEmpresaActionPerformed

    private void ItemListarPorNumeroVendedoresEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorNumeroVendedoresEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorNumeroVendedoresEmpresaActionPerformed

    private void ItemListarPorNUmeroSedesEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorNUmeroSedesEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorNUmeroSedesEmpresaActionPerformed

    private void ItemListarPorCapitalPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorCapitalPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorCapitalPaisActionPerformed

    private void ItemListarPorNumeroHabitantesPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorNumeroHabitantesPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorNumeroHabitantesPaisActionPerformed

    private void ItemListarPorPibPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorPibPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorPibPaisActionPerformed

    private void ItemListarPorDireccionVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorDireccionVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorDireccionVendedorActionPerformed

    private void ItemListarPorNumeroTrabajosVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemListarPorNumeroTrabajosVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemListarPorNumeroTrabajosVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemAgregarArea;
    private javax.swing.JMenuItem ItemAgregarAsesor;
    private javax.swing.JMenuItem ItemAgregarEmpresa;
    private javax.swing.JMenuItem ItemAgregarHolding;
    private javax.swing.JMenuItem ItemAgregarPais;
    private javax.swing.JMenuItem ItemAgregarSede;
    private javax.swing.JMenuItem ItemAgregarVendedor;
    private javax.swing.JMenuItem ItemBuscarArea;
    private javax.swing.JMenuItem ItemBuscarAsesor;
    private javax.swing.JMenuItem ItemBuscarEmpresa;
    private javax.swing.JMenuItem ItemBuscarHolding;
    private javax.swing.JMenuItem ItemBuscarPais;
    private javax.swing.JMenuItem ItemBuscarSede;
    private javax.swing.JMenuItem ItemBuscarVendedor;
    private javax.swing.JMenuItem ItemEditarArea;
    private javax.swing.JMenuItem ItemEditarAsesor;
    private javax.swing.JMenuItem ItemEditarEmpresa;
    private javax.swing.JMenuItem ItemEditarHolding;
    private javax.swing.JMenuItem ItemEditarPais;
    private javax.swing.JMenuItem ItemEditarSede;
    private javax.swing.JMenuItem ItemEditarVendedor;
    private javax.swing.JMenuItem ItemEliminarArea;
    private javax.swing.JMenuItem ItemEliminarAsesor;
    private javax.swing.JMenuItem ItemEliminarEmpresa;
    private javax.swing.JMenuItem ItemEliminarHolding;
    private javax.swing.JMenuItem ItemEliminarPais;
    private javax.swing.JMenuItem ItemEliminarSede;
    private javax.swing.JMenuItem ItemEliminarVendedor;
    private javax.swing.JMenuItem ItemListarPorCapitalPais;
    private javax.swing.JMenuItem ItemListarPorCiudadLocalizaSede;
    private javax.swing.JMenuItem ItemListarPorDireccionAsesor;
    private javax.swing.JMenuItem ItemListarPorDireccionVendedor;
    private javax.swing.JMenuItem ItemListarPorFacturacionAnualEmpresa;
    private javax.swing.JMenuItem ItemListarPorFechaEntradaEmpresa;
    private javax.swing.JMenuItem ItemListarPorFechaInicioAsesor;
    private javax.swing.JMenuItem ItemListarPorIdArea;
    private javax.swing.JMenuItem ItemListarPorIdAsesor;
    private javax.swing.JMenuItem ItemListarPorIdEmpresa;
    private javax.swing.JMenuItem ItemListarPorIdHolding;
    private javax.swing.JMenuItem ItemListarPorIdPais;
    private javax.swing.JMenuItem ItemListarPorIdSede;
    private javax.swing.JMenuItem ItemListarPorIdVendedor;
    private javax.swing.JMenuItem ItemListarPorNUmeroSedesEmpresa;
    private javax.swing.JMenuItem ItemListarPorNombreArea;
    private javax.swing.JMenuItem ItemListarPorNombreAsesor;
    private javax.swing.JMenuItem ItemListarPorNombreEmpresa;
    private javax.swing.JMenuItem ItemListarPorNombreHolding;
    private javax.swing.JMenuItem ItemListarPorNombrePais;
    private javax.swing.JMenuItem ItemListarPorNombreVendedor;
    private javax.swing.JMenuItem ItemListarPorNumeroHabitantesPais;
    private javax.swing.JMenuItem ItemListarPorNumeroTrabajosVendedor;
    private javax.swing.JMenuItem ItemListarPorNumeroVendedoresEmpresa;
    private javax.swing.JMenuItem ItemListarPorPibPais;
    private javax.swing.JMenuItem ItemListarPorTitulaciónAsesor;
    private javax.swing.JMenuItem ItemListarTodoArea;
    private javax.swing.JMenuItem ItemListarTodoAsesor;
    private javax.swing.JMenuItem ItemListarTodoEmpresa;
    private javax.swing.JMenuItem ItemListarTodoHolding;
    private javax.swing.JMenuItem ItemListarTodoPais;
    private javax.swing.JMenuItem ItemListarTodoSede;
    private javax.swing.JMenuItem ItemListarTodoVendedor;
    private javax.swing.JMenu MenuArea;
    private javax.swing.JMenu MenuAsesor;
    private javax.swing.JMenu MenuEmpresa;
    private javax.swing.JMenu MenuHolding;
    private javax.swing.JMenu MenuPais;
    private javax.swing.JMenu MenuSede;
    private javax.swing.JMenu MenuVendedor;
    private javax.swing.JMenu SubMenuReportesArea;
    private javax.swing.JMenu SubMenuReportesAsesor;
    private javax.swing.JMenu SubMenuReportesEmpresa;
    private javax.swing.JMenu SubMenuReportesHolding;
    private javax.swing.JMenu SubMenuReportesPais;
    private javax.swing.JMenu SubMenuReportesSede;
    private javax.swing.JMenu SubMenuReportesVendedor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    // End of variables declaration//GEN-END:variables

    private void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/icono.png")));
    }
}
