/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package co.edu.ude.poo.empresas.vistas.gui;

import co.edu.ude.poo.empresas.modelo.entidades.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class VentanaCrudEmpresa extends javax.swing.JDialog {
    Empresa empresa;
    /**
     * Creates new form VentanaCrudEmpresa
     */
    public VentanaCrudEmpresa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        EtiquetaId = new javax.swing.JLabel();
        CampoId = new javax.swing.JTextField();
        EtiquetaNombre = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        EtiquetaFechaInicio = new javax.swing.JLabel();
        CampoFechaInicio = new javax.swing.JTextField();
        EtiquetaFacturacionAnual = new javax.swing.JLabel();
        CampoFacturacionAnual = new javax.swing.JTextField();
        EtiquetaNumeroVendedores = new javax.swing.JLabel();
        CampoNumeroVendedores = new javax.swing.JTextField();
        EtiquetaNumeroSedes = new javax.swing.JLabel();
        CampoNumeroSedes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BotonAgregar = new javax.swing.JButton();
        BotonBuscar = new javax.swing.JButton();
        BotonEditar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();
        BotonListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Area");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Formulario Empresa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)), "Datos de la Empresa:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 102, 204))); // NOI18N

        EtiquetaId.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        EtiquetaId.setText("ID:");

        CampoId.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        CampoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoIdActionPerformed(evt);
            }
        });

        EtiquetaNombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        EtiquetaNombre.setText("NOMBRE:");

        CampoNombre.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        CampoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNombreActionPerformed(evt);
            }
        });

        EtiquetaFechaInicio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        EtiquetaFechaInicio.setText("FECHA DE ENTRADA:");

        CampoFechaInicio.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        CampoFechaInicio.setText("aaaa/mm/dd");
        CampoFechaInicio.setToolTipText("");
        CampoFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoFechaInicioActionPerformed(evt);
            }
        });

        EtiquetaFacturacionAnual.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        EtiquetaFacturacionAnual.setText("FACTURACION ANUAL:");

        CampoFacturacionAnual.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        CampoFacturacionAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoFacturacionAnualActionPerformed(evt);
            }
        });

        EtiquetaNumeroVendedores.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        EtiquetaNumeroVendedores.setText("NUMERO DE VENDEDORES:");

        CampoNumeroVendedores.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        CampoNumeroVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNumeroVendedoresActionPerformed(evt);
            }
        });

        EtiquetaNumeroSedes.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        EtiquetaNumeroSedes.setText("NUMERO DE SEDES:");

        CampoNumeroSedes.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        CampoNumeroSedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNumeroSedesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 48, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EtiquetaFechaInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EtiquetaNumeroSedes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoNumeroSedes, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EtiquetaFacturacionAnual)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoFacturacionAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EtiquetaId)
                                    .addComponent(EtiquetaNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(CampoId, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                    .addComponent(CampoNombre)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EtiquetaNumeroVendedores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoNumeroVendedores)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtiquetaId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaNombre)
                    .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaFechaInicio)
                    .addComponent(CampoFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoFacturacionAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtiquetaFacturacionAnual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EtiquetaNumeroVendedores)
                    .addComponent(CampoNumeroVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNumeroSedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EtiquetaNumeroSedes))
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/empresa.png"))); // NOI18N

        BotonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/guardar24px.png"))); // NOI18N
        BotonAgregar.setText("AGREGAR");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });

        BotonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/buscar24px.png"))); // NOI18N
        BotonBuscar.setText("BUSCAR");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        BotonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/editar24px.png"))); // NOI18N
        BotonEditar.setText("EDITAR");
        BotonEditar.setEnabled(false);
        BotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarActionPerformed(evt);
            }
        });

        BotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/eliminar24px.png"))); // NOI18N
        BotonEliminar.setText("ELIMINAR");
        BotonEliminar.setEnabled(false);
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        BotonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/limpiar24px.png"))); // NOI18N
        BotonLimpiar.setText("LIMPIAR");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        BotonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/cancel24px.png"))); // NOI18N
        BotonCancelar.setText("CANCELAR");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        BotonListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/ude/poo/empresas/vistas/iconos/reporte24px.png"))); // NOI18N
        BotonListar.setText("LISTAR");
        BotonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGap(67, 67, 67)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(BotonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonCancelar)))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(72, 72, 72)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAgregar)
                    .addComponent(BotonBuscar)
                    .addComponent(BotonEditar)
                    .addComponent(BotonEliminar)
                    .addComponent(BotonLimpiar)
                    .addComponent(BotonCancelar)
                    .addComponent(BotonListar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoIdActionPerformed

    private void CampoFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoFechaInicioActionPerformed

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        //recuperar los datos ingresados en los campos del formulario
        String id = CampoId.getText();        
        String nombre_empresa = CampoNombre.getText();
        String fecha_entrada_holding = CampoFechaInicio.getText();
        int facturacion_anual = Integer.parseInt(CampoFacturacionAnual.getText());
        int numero_vendedores = Integer.parseInt(CampoNumeroVendedores.getText());
        int num_sedes = Integer.parseInt(CampoNumeroSedes.getText());
        //crear un objeto (variable tipo empresa)
        Empresa empresa = new Empresa();
        empresa.setId(id);
        empresa.setNombre_empresa(nombre_empresa);
        empresa.setFecha_entrada_holding(fecha_entrada_holding);
        empresa.setFacturacion_anual(facturacion_anual);
        empresa.setNumero_vendedores(numero_vendedores);
        empresa.setNum_sedes(num_sedes);
        //validar si el Map existe
        if(Empresa.getEmpresaBD() == null){
            Empresa.setEmpresaBD(new HashMap<>());
        }
        //validar si el Map ya tiene el empresa guardada
        if(Empresa.getEmpresaBD().containsKey(id)){
            String msj = "Ya existe el empresa con id: " + id;
            JOptionPane.showMessageDialog(this, msj);
        }else if(id.isEmpty() || id.length() == 0 ||    //verificar si algun campo está vacio
                nombre_empresa.isEmpty() || nombre_empresa.length() == 0 ||
                fecha_entrada_holding.isEmpty() || fecha_entrada_holding.length() == 0 ||
                facturacion_anual == 0 ||
                numero_vendedores == 0 ||
                num_sedes == 0){
            String msj = "Hay campo(s) vacio(s), no se guardara nada hasta que el problema se solucione";
            JOptionPane.showMessageDialog(this, msj);
        }else if(!fecha_entrada_holding.matches("^[0-9]{4}/[0-9]{2}/[0-9]{2}")){
            String msj = "La fecha de inicio no es valida \n "
                    + "no se guardara nada hasta que el problema se solucione \n "
                    + "El formato valido es: aaaa/mm/dd";
            JOptionPane.showMessageDialog(this, msj);
        }else if(!nombre_empresa.matches("^[\\p{L}\\s]+$")){
            String msj = "El nombre no es valido\n "
                    + "no se guardara nada hasta que el problema se solucione \n ";
            JOptionPane.showMessageDialog(this, msj);
        }else if(!CampoFacturacionAnual.getText().matches("\\d+")){
            String msj = "La facturacion no es valida \n "
                    + "no se guardara nada hasta que el problema se solucione \n ";
            JOptionPane.showMessageDialog(this, msj);
        }else if(!CampoNumeroVendedores.getText().matches("\\d+")){
            String msj = "El numero de vendedores no es valido \n "
                    + "no se guardara nada hasta que el problema se solucione \n ";
            JOptionPane.showMessageDialog(this, msj);
        }else if(!CampoNumeroSedes.getText().matches("\\d+")){
            String msj = "El numero de sedes no es valido \n "
                    + "no se guardara nada hasta que el problema se solucione \n ";
            JOptionPane.showMessageDialog(this, msj);
        }else{
            //se pregunta si se quiere guardar la informacion
            int option = JOptionPane.showConfirmDialog(this
            , "Guardar la informacion?", "confirmar guardado"
            , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(option == JOptionPane.YES_OPTION){
                //se guarda el empresa si no existia
                Empresa.getEmpresaBD().put(id, empresa);
                //obtenemos el numero de empresas
                int cuentaEmpresas = Empresa.getEmpresaBD().size();
                String msj = "el empresa fue guardada. "
                        + "Existen: " + cuentaEmpresas + " empresa(s)";
                JOptionPane.showMessageDialog(this, msj);
                limpiarCampos();
            }
            
        }        
    }//GEN-LAST:event_BotonAgregarActionPerformed

    public void limpiarCampos(){
        CampoId.setText("");
        CampoFechaInicio.setText("aaaa/mm/dd");
        CampoNombre.setText("");
        CampoFacturacionAnual.setText("");
        CampoNumeroVendedores.setText("");
        CampoNumeroSedes.setText("");
        
        BotonEditar.setEnabled(false);
        BotonEliminar.setEnabled(false);
    }
    
    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        //recuperar los datos ingresados en los campos del formulario
        String id = CampoId.getText();
        String fecha_entrada_holding = CampoFechaInicio.getText();
        String nombre_empresa = CampoNombre.getText();
        String facturacion_anual = CampoFacturacionAnual.getText();        
        String numero_vendedores = CampoNumeroVendedores.getText();
        String num_sedes = CampoNumeroSedes.getText();
        //verificar si el map existe o si esta vacio
        if(Empresa.getEmpresaBD() == null || Empresa.getEmpresaBD().isEmpty()){
            String msj = "no hay usuarios en la BD";
            JOptionPane.showMessageDialog(this, msj);
        }else{
            //buscar el empresa a partir del id
            if(Empresa.getEmpresaBD().containsKey(id)){
                this.empresa = Empresa.getEmpresaBD().get(id);
                CampoFechaInicio.setText(this.empresa.getFecha_entrada_holding());
                CampoNombre.setText(this.empresa.getNombre_empresa());
                CampoFacturacionAnual.setText(Integer.toString(this.empresa.getFacturacion_anual()));
                CampoNumeroVendedores.setText(Integer.toString(this.empresa.getNumero_vendedores()));
                CampoNumeroSedes.setText(Integer.toString(this.empresa.getNum_sedes()));
            //se activan los botones si la busqueda fue exitosa
            BotonEditar.setEnabled(true);
            BotonEliminar.setEnabled(true);
            }else if(id.isEmpty() || id.length() == 0){
                String msj = "El campo id está vacio, es requerido para realizar la busqueda";
                JOptionPane.showMessageDialog(this, msj);
            }else{
                BotonEditar.setEnabled(false);
                BotonEliminar.setEnabled(false);
                String msj = "no hay empresas en la BD con ese id: " + id;
                JOptionPane.showMessageDialog(this, msj);
                limpiarCampos();
            }
        }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        //se pregunta si se quiere guardar la informacion
            int option = JOptionPane.showConfirmDialog(this
            , "Limpiar el formulario?", "confirmar limpieza"
            , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(option == JOptionPane.YES_OPTION){
                String msj = "Formulario limpiado con exito";
                JOptionPane.showMessageDialog(this, msj);
                limpiarCampos();
            }
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
        int option = JOptionPane.showConfirmDialog(this
            , "Cerrar ventana?", "confirmar cierre"
            , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(option == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
        //validamos que el campo cedula tenga algun dato
        if(CampoId.getText() == null || CampoId.getText().isEmpty()){
            String msj = "Para editar introduzca el id";
            JOptionPane.showMessageDialog(this, msj);
            limpiarCampos();
            return;
        }
        //validar que el id coincida con el id consultado previamente
        if(CampoId.getText().equals(this.empresa.getId()) != true){
            String msj = "El id no coincide con el id consultado previamente";
            JOptionPane.showMessageDialog(this, msj);
            limpiarCampos();
            return;
        }
        
        //validando que el empresa sí sea editado
        if(CampoFechaInicio.getText().equals(this.empresa.getFecha_entrada_holding()) == true && 
           CampoNombre.getText().equals(this.empresa.getNombre_empresa()) == true && 
           CampoFacturacionAnual.getText().equals(Integer.toString(this.empresa.getFacturacion_anual())) == true && 
           CampoNumeroSedes.getText().equals(Integer.toString(this.empresa.getNum_sedes())) == true &&
           CampoNumeroVendedores.getText().equals(Integer.toString(this.empresa.getNumero_vendedores())) == true){
            String msj = "No se ha cambiado nada";
            JOptionPane.showMessageDialog(this, msj);
            return;
        }
        
        //recuperamos el texto que haya en el CampoId y el mapa nos devuelve el empresa con ese id
        this.empresa = Empresa.getEmpresaBD().get(CampoId.getText());
        
        //se pregunta si se quiere guardar la informacion
            int option = JOptionPane.showConfirmDialog(this
            , "Guardar los cambios?", "confirmar cambios"
            , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(option == JOptionPane.YES_OPTION){
                //recuperar los numevos datos ingresados en el formulario
                String id = CampoId.getText();
                String fecha_entrada_holding = CampoFechaInicio.getText();
                String nombre_empresa = CampoNombre.getText();
                int facturacion_anual = Integer.parseInt(CampoFacturacionAnual.getText());
                int num_sedes = Integer.parseInt(CampoNumeroSedes.getText());
                int numero_vendedores = Integer.parseInt(CampoNumeroVendedores.getText());

                //Cambiar los datos anteriores del empresa por los datos nuevos
                this.empresa.setFecha_entrada_holding(String.valueOf(fecha_entrada_holding));
                this.empresa.setNombre_empresa(String.valueOf(nombre_empresa));
                this.empresa.setFacturacion_anual(facturacion_anual);
                this.empresa.setNum_sedes(num_sedes);
                this.empresa.setNumero_vendedores(numero_vendedores);

                //Guardamos el empresa con los nuevos datos
                Empresa.getEmpresaBD().put(this.empresa.getId(), this.empresa);

                //mostramos el mensaje
                String msj = "Empresa modificado con exito";
                JOptionPane.showMessageDialog(this, msj);
                limpiarCampos();
            }
    }//GEN-LAST:event_BotonEditarActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        //validamos que el campo Id tenga algun dato
        if(CampoId.getText() == null || CampoId.getText().isEmpty()){
            String msj = "Para editar introduzca el id";
            JOptionPane.showMessageDialog(this, msj);
            limpiarCampos();
            return;
        }
        
        //validar que el id coincida con el id consultado previamente
        if(CampoId.getText().equals(this.empresa.getId()) != true){
            String msj = "El id no coincide con el id consultado previamente";
            JOptionPane.showMessageDialog(this, msj);
            limpiarCampos();
            return;
        }
        String msj = "Seguro desea eliminar el empresa?";
        int respuesta = JOptionPane.showConfirmDialog(this, msj
                , "CONFIRMAR ELIMINACION", JOptionPane.YES_NO_OPTION
                , JOptionPane.QUESTION_MESSAGE);
        if(respuesta == JOptionPane.YES_OPTION){
            Empresa.getEmpresaBD().remove(this.empresa.getId());
            int total = Empresa.getEmpresaBD().size();
            String msj2 = "Empresa eliminada exitosamente, hay " + total + " empresa(s)";
            JOptionPane.showMessageDialog(this, msj2);
            limpiarCampos();
        }
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void BotonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListarActionPerformed
        if(Empresa.getEmpresaBD() == null || Empresa.getEmpresaBD().isEmpty()){
            JOptionPane.showMessageDialog(this, "no hay usuarios para listar"
            , "RESULTADO NEGATIVO", JOptionPane.WARNING_MESSAGE);
            return;
        }
            
        this.dispose();
            
        VentanaReporteEmpresa ventanaReporte = new VentanaReporteEmpresa(new JFrame(), true);
        ventanaReporte.setLocationRelativeTo(this);
        ventanaReporte.setVisible(true);
        
    }//GEN-LAST:event_BotonListarActionPerformed

    private void CampoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNombreActionPerformed

    private void CampoFacturacionAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoFacturacionAnualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoFacturacionAnualActionPerformed

    private void CampoNumeroSedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNumeroSedesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNumeroSedesActionPerformed

    private void CampoNumeroVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNumeroVendedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNumeroVendedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCrudEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCrudEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCrudEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCrudEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaCrudEmpresa dialog = new VentanaCrudEmpresa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonListar;
    private javax.swing.JTextField CampoFacturacionAnual;
    private javax.swing.JTextField CampoFechaInicio;
    private javax.swing.JTextField CampoId;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JTextField CampoNumeroSedes;
    private javax.swing.JTextField CampoNumeroVendedores;
    private javax.swing.JLabel EtiquetaFacturacionAnual;
    private javax.swing.JLabel EtiquetaFechaInicio;
    private javax.swing.JLabel EtiquetaId;
    private javax.swing.JLabel EtiquetaNombre;
    private javax.swing.JLabel EtiquetaNumeroSedes;
    private javax.swing.JLabel EtiquetaNumeroVendedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
